version: '3'

services:
  frontend:
    build:
      context: ./taskcraft-client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: always

  backend:
    build: ./taskcraft-server
    ports:
      - '5002:5000'
    env_file:
      - ./taskcraft-server/.env
    restart: always
